/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FlowFields {
    }
    interface GalleryItem {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLFlowFieldsElement extends Components.FlowFields, HTMLStencilElement {
    }
    var HTMLFlowFieldsElement: {
        prototype: HTMLFlowFieldsElement;
        new (): HTMLFlowFieldsElement;
    };
    interface HTMLGalleryItemElement extends Components.GalleryItem, HTMLStencilElement {
    }
    var HTMLGalleryItemElement: {
        prototype: HTMLGalleryItemElement;
        new (): HTMLGalleryItemElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "flow-fields": HTMLFlowFieldsElement;
        "gallery-item": HTMLGalleryItemElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FlowFields {
    }
    interface GalleryItem {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "flow-fields": FlowFields;
        "gallery-item": GalleryItem;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "flow-fields": LocalJSX.FlowFields & JSXBase.HTMLAttributes<HTMLFlowFieldsElement>;
            "gallery-item": LocalJSX.GalleryItem & JSXBase.HTMLAttributes<HTMLGalleryItemElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
